#!/bin/sh

set -e

cleanup() {
    echo "Failed to switch to stock"

    # Clean up firmware files
    rm -r "$BINFILE" "$ZIPFILE" /user-resource/update

    # Restart services
    service klipper start
    service moonraker start
    service mjpg-streamer start

    exit 1
}
trap cleanup EXIT

# ver 1.1.46
FW_URL="https://download.chitubox.com/chitusystems/chitusystems/public/printer/firmware/release/1/ca8e1d9a20974a5896f8f744e780a8a7/1/01.01.46/2025-10-22/f9bd2b9b1926408ca238de8e7eac69b6.bin"
KEY="78B6A614B6B6E361DC84D705B7FDDA33C967DDF2970A689F8156F78EFE0B1FCE"
IV="54E37626B9A699403064111F77858049"
BINFILE="/user-resource/update.bin"
ZIPFILE="/user-resource/update.zip"
SWUFILE="/user-resource/update/update.swu"

service mjpg-streamer stop
service moonraker stop
service klipper stop

# Download firmware
curl -k -o "$BINFILE" -L "$FW_URL"

# Decrypt firmware
swu-decrypt.py "$BINFILE" "$KEY" "$IV" "$ZIPFILE"
unzip "$ZIPFILE" -d /user-resource

# Flash stock bootloader
restore-mcu-firmware

# Install firmware
flash "$SWUFILE"

# Revert stock bootcmd
fw_setenv bootcmd "run setargs_mmc boot_dsp0 boot_normal"

# Clean up firmware files
rm -r "$BINFILE" "$ZIPFILE" /user-resource/update

sleep 3

reboot
